AllCops:
  Exclude:
    - 'spec/**/*'
    - 'db/**'
    - 'bin/**'
    - 'app/javascript/**'
    - 'config/**'

  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false
