AllCops:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'app/javascript/**'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'lib/assets/**/*'

  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
